config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  resources :facebookposts
  resources :tumblrposts
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/sessions/destroy', to: "sessions#destroy"
  resources :tweets

  root to: "welcome#index"

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user

  validates :user_id, :status, presence: true

  before_create :post_to_twitter


  def post_to_twitter
    user.twitter.update(status)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
    @tweets_timeline = current_user.twitter.home_timeline
    @tweet = Tweet.new
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweets_path, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:user_id, :status)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.haml
= form_for(@tweet) do |f|
  - if @tweet.errors.any?
    #error_explanation
      %h2
        = pluralize(@tweet.errors.count, "error")
        prohibited this tweet from being saved:
      %ul
        - @tweet.errors.full_messages.each do |message|
          %li= message
  .content_input.clearfix
    = image_tag(current_user.profile_image)
    = f.text_area :status, placeholder: "What's happening?"
  .content_submit.clearfix
    = f.submit class: "button"

app/views/tweets/edit.html.haml
%h1 Editing Tweet
= render 'form'
= link_to 'Show', @tweet
|
= link_to 'Back', tweets_path

app/views/tweets/index.html.haml
%nav.header_twitter.clearfix
  .wrapper
    .nav_left
      = link_to tweets_path do
        %p.welcome_message
          Hi Yongyi
    .nav_mid
      = image_tag ("https://s3.amazonaws.com/webimagexu/social_media_engine/twitter-256.jpg"), class: "logo"
    .nav_right
      %ul
        %li
          = link_to "Home", root_path
        %li
          = link_to "Twitter Home", tweets_path
        %li
          = link_to "Log Out", sessions_destroy_path
.content_twitter
  .wrapper
    .content_container
      = render "tweets/form"

      - @tweets_timeline.each do |tweet|
        .content_tweet.clearfix
          = image_tag (current_user.profile_image)
          .content
            %span.tweet_name
              %h4= current_user.name
              %h5
                @
                = current_user.nickname
            %span.tweet_message
              %p= tweet.text

app/views/tweets/new.html.haml
%h1 New Tweet
= render 'form'
= link_to 'Back', tweets_path

app/views/tweets/show.html.haml
%p#notice= notice
%p
  %strong Status:
  = @tweet.status
= link_to 'Edit', edit_tweet_path(@tweet)
|
= link_to 'Back', tweets_path