config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  resources :facebookposts
  resources :tumblrposts
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/sessions/destroy', to: "sessions#destroy"
  resources :tweets

  root to: "welcome#index"

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.haml
%nav.header_home.clearfix
  .wrapper
    .logo
      %h2 Social Media Engine
.content_home
  .wrapper
    .title
      %h3 Select a Social Site to Log In
    %hr/
    .row_home.clearfix
      - if current_user.present? && current_user.provider == "facebook"
        = link_to facebookposts_path do
          .social_icon
            = image_tag("https://s3.amazonaws.com/webimagexu/social_media_engine/social_facebook_box_blue.png")
      - else
        = link_to "auth/facebook" do
          .social_icon
            = image_tag("https://s3.amazonaws.com/webimagexu/social_media_engine/social_facebook_box_blue.png")

      - if current_user.present? && current_user.provider == "twitter"
        = link_to tweets_path do
          .social_icon
            = image_tag("https://s3.amazonaws.com/webimagexu/social_media_engine/twitter-256.jpg")
      - else
        = link_to "auth/twitter" do
          .social_icon
            = image_tag("https://s3.amazonaws.com/webimagexu/social_media_engine/twitter-256.jpg")