config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  resources :facebookposts
  resources :tumblrposts
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/sessions/destroy', to: "sessions#destroy"
  resources :tweets

  root to: "welcome#index"

end

app/models/tumblrpost.rb
class Tumblrpost < ActiveRecord::Base
end

app/controllers/tumblrposts_controller.rb
class TumblrpostsController < ApplicationController
  before_action :set_tumblrpost, only: [:show, :edit, :update, :destroy]

  # GET /tumblrposts
  # GET /tumblrposts.json
  def index
    @tumblrposts = Tumblrpost.all
  end

  # GET /tumblrposts/1
  # GET /tumblrposts/1.json
  def show
  end

  # GET /tumblrposts/new
  def new
    @tumblrpost = Tumblrpost.new
  end

  # GET /tumblrposts/1/edit
  def edit
  end

  # POST /tumblrposts
  # POST /tumblrposts.json
  def create
    @tumblrpost = Tumblrpost.new(tumblrpost_params)

    respond_to do |format|
      if @tumblrpost.save
        format.html { redirect_to @tumblrpost, notice: 'Tumblrpost was successfully created.' }
        format.json { render :show, status: :created, location: @tumblrpost }
      else
        format.html { render :new }
        format.json { render json: @tumblrpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tumblrposts/1
  # PATCH/PUT /tumblrposts/1.json
  def update
    respond_to do |format|
      if @tumblrpost.update(tumblrpost_params)
        format.html { redirect_to @tumblrpost, notice: 'Tumblrpost was successfully updated.' }
        format.json { render :show, status: :ok, location: @tumblrpost }
      else
        format.html { render :edit }
        format.json { render json: @tumblrpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tumblrposts/1
  # DELETE /tumblrposts/1.json
  def destroy
    @tumblrpost.destroy
    respond_to do |format|
      format.html { redirect_to tumblrposts_url, notice: 'Tumblrpost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tumblrpost
      @tumblrpost = Tumblrpost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tumblrpost_params
      params.require(:tumblrpost).permit(:user_id, :title, :body)
    end
end

app/helpers/tumblrposts_helper.rb
module TumblrpostsHelper
end

app/views/tumblrposts/_form.html.haml
= form_for(@tumblrpost) do |f|
  - if @tumblrpost.errors.any?
    #error_explanation
      %h2
        = pluralize(@tumblrpost.errors.count, "error")
        prohibited this tumblrpost from being saved:
      %ul
        - @tumblrpost.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :user_id
    %br/
    = f.number_field :user_id
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :body
    %br/
    = f.text_area :body
  .actions
    = f.submit

app/views/tumblrposts/edit.html.haml
%h1 Editing Tumblrpost
= render 'form'
= link_to 'Show', @tumblrpost
|
= link_to 'Back', tumblrposts_path

app/views/tumblrposts/index.html.haml
%p#notice= notice
%h1 Listing Tumblrposts
%table
  %thead
    %tr
      %th User
      %th Title
      %th Body
      %th{:colspan => "3"}
  %tbody
    - @tumblrposts.each do |tumblrpost|
      %tr
        %td= tumblrpost.user_id
        %td= tumblrpost.title
        %td= tumblrpost.body
        %td= link_to 'Show', tumblrpost
        %td= link_to 'Edit', edit_tumblrpost_path(tumblrpost)
        %td= link_to 'Destroy', tumblrpost, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Tumblrpost', new_tumblrpost_path

app/views/tumblrposts/new.html.haml
%h1 New Tumblrpost
= render 'form'
= link_to 'Back', tumblrposts_path

app/views/tumblrposts/show.html.haml
%p#notice= notice
%p
  %strong User:
  = @tumblrpost.user_id
%p
  %strong Title:
  = @tumblrpost.title
%p
  %strong Body:
  = @tumblrpost.body
= link_to 'Edit', edit_tumblrpost_path(@tumblrpost)
|
= link_to 'Back', tumblrposts_path