config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  resources :facebookposts
  resources :tumblrposts
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/sessions/destroy', to: "sessions#destroy"
  resources :tweets

  root to: "welcome#index"

end

app/models/facebookpost.rb
class Facebookpost < ActiveRecord::Base

  belongs_to :user

  validates :user_id, :body, presence: true



end

app/controllers/facebookposts_controller.rb
class FacebookpostsController < ApplicationController
  before_action :set_facebookpost, only: [:show, :edit, :update, :destroy]

  # GET /facebookposts
  # GET /facebookposts.json
  def index
    @facebookposts = Facebookpost.all
    @feeds = current_user.facebook.get_connections("me", "feed?fields=message,link,privacy")
    @facebookpost = Facebookpost.new
  end

  # GET /facebookposts/1
  # GET /facebookposts/1.json
  def show
  end

  # GET /facebookposts/new
  def new
    @facebookpost = Facebookpost.new
  end

  # GET /facebookposts/1/edit
  def edit
  end

  # POST /facebookposts
  # POST /facebookposts.json
  def create
    @facebookpost = Facebookpost.new(facebookpost_params)
    current_user.facebook.put_wall_post(:body)
    respond_to do |format|
      if @facebookpost.save
        format.html { redirect_to facebookposts_path, notice: 'Facebookpost was successfully created.' }
        format.json { render :show, status: :created, location: @facebookpost }
      else
        format.html { render :new }
        format.json { render json: @facebookpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facebookposts/1
  # PATCH/PUT /facebookposts/1.json
  def update
    respond_to do |format|
      if @facebookpost.update(facebookpost_params)
        format.html { redirect_to @facebookpost, notice: 'Facebookpost was successfully updated.' }
        format.json { render :show, status: :ok, location: @facebookpost }
      else
        format.html { render :edit }
        format.json { render json: @facebookpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facebookposts/1
  # DELETE /facebookposts/1.json
  def destroy
    @facebookpost.destroy
    respond_to do |format|
      format.html { redirect_to facebookposts_url, notice: 'Facebookpost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_facebookpost
      @facebookpost = Facebookpost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def facebookpost_params
      params.require(:facebookpost).permit(:user_id, :body)
    end
end

app/helpers/facebookposts_helper.rb
module FacebookpostsHelper
end

app/views/facebookposts/_form.html.haml
= form_for(@facebookpost) do |f|
  - if @facebookpost.errors.any?
    #error_explanation
      %h2
        = pluralize(@facebookpost.errors.count, "error")
        prohibited this facebookpost from being saved:
      %ul
        - @facebookpost.errors.full_messages.each do |message|
          %li= message
  = f.text_field :user_id, value: "1", class: "hide"
  .input.clearfix
    = image_tag (current_user.profile_image)
    = f.text_area :body, placeholder: "What's on your mind?"
  .buttons_group.clearfix
    = f.submit "Post", class: "button_facebook"

app/views/facebookposts/edit.html.haml
%h1 Editing Facebookpost
= render 'form'
= link_to 'Show', @facebookpost
|
= link_to 'Back', facebookposts_path

app/views/facebookposts/index.html.haml
:javascript
  window.fbAsyncInit = function() {
      FB.init({
          appId      : '1667117996948209',
          xfbml      : true,
          version    : 'v2.7'
      });
  };

  (function(d, s, id){
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) {return;}
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js";
      fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));


%nav.header_facebook.clearfix
  .wrapper
    .nav_left
      = link_to facebookposts_path do
        %p.welcome_message
          Hi Yongyi
    .nav_mid
      = image_tag ("https://s3.amazonaws.com/webimagexu/social_media_engine/social_facebook_box_blue.png"), class: "logo"
    .nav_right
      %ul
        %li
          = link_to "Home", root_path
        %li
          = link_to "Facebook Home", facebookposts_path
        %li
          = link_to "Log Out", sessions_destroy_path
.content_facebook
  .wrapper
    .content_container
      .content_box.content_input.clearfix
        = render "facebookposts/form"
      - @feeds.each do |feed|
        - if feed["message"].present? && feed["privacy"]["value"]=="EVERYONE"
          - if feed["link"].present?
            .fb-post{"data-href" => feed["link"]}
          - else
            .content_box
              .status_profile.clearfix
                = image_tag(current_user.profile_image)
                %h3= current_user.name
                %p some time ago
              .status_message.clearfix
                %p= feed["message"]

app/views/facebookposts/new.html.haml
%h1 New Facebookpost
= render 'form'
= link_to 'Back', facebookposts_path

app/views/facebookposts/show.html.haml
%p#notice= notice
%p
  %strong User:
  = @facebookpost.user_id
%p
  %strong Body:
  = @facebookpost.body
= link_to 'Edit', edit_facebookpost_path(@facebookpost)
|
= link_to 'Back', facebookposts_path